Repository openstack-k8s-operators/ironic-operator, pull requests merged in 2022-12, with the labels that each got.

#50 Only download IPA in imagetter.yaml
  templates/ironic/bin/imagetter.yaml
Labels: approved

#51 Add handling for top level NodeSelector
  api/bases/ironic.openstack.org_ironicapis.yaml
  api/bases/ironic.openstack.org_ironicconductors.yaml
  api/bases/ironic.openstack.org_ironics.yaml
  api/v1beta1/ironic_types.go
  api/v1beta1/ironicapi_types.go
  api/v1beta1/ironicconductor_types.go
  config/crd/bases/ironic.openstack.org_ironicapis.yaml
  config/crd/bases/ironic.openstack.org_ironicconductors.yaml
  config/crd/bases/ironic.openstack.org_ironics.yaml
  controllers/ironic_controller.go
Labels: lgtm

#57 Add RabbitMQ transportURL support
  api/bases/ironic.openstack.org_ironicapis.yaml
  api/bases/ironic.openstack.org_ironicconductors.yaml
  api/bases/ironic.openstack.org_ironics.yaml
  api/v1beta1/conditions.go
  api/v1beta1/ironic_types.go
  api/v1beta1/ironicapi_types.go
  api/v1beta1/ironicconductor_types.go
  config/crd/bases/ironic.openstack.org_ironicapis.yaml
  config/crd/bases/ironic.openstack.org_ironicconductors.yaml
  config/crd/bases/ironic.openstack.org_ironics.yaml
  controllers/ironic_controller.go
  controllers/ironicapi_controller.go
  controllers/ironicconductor_controller.go
  go.mod
  go.sum
  main.go
  pkg/ironic/initcontainer.go
  pkg/ironicapi/deployment.go
  pkg/ironicconductor/statefulset.go
  templates/ironic/bin/init.sh
Labels: lgtm, ok-to-test

#58 Refresh dependencies, refresh CRDs
  api/bases/ironic.openstack.org_ironicapis.yaml
  api/bases/ironic.openstack.org_ironicconductors.yaml
  api/bases/ironic.openstack.org_ironics.yaml
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/ironic.openstack.org_ironicapis.yaml
  config/crd/bases/ironic.openstack.org_ironicconductors.yaml
  config/crd/bases/ironic.openstack.org_ironics.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
Labels: approved

#59 add_service_db_finalizer_logic
  controllers/ironic_controller.go
Labels: approved

#60 Add Julia, Harald to OWNERS
  OWNERS
Labels: approved

#66 Refresh openstack dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved

#67 api go.mod, PROJECT fixes
  PROJECT
  go.mod
Labels: approved
