Repository openstack-k8s-operators/ironic-operator, pull requests merged in 2023-01, with the labels that each got.

#68 Use public endpoint for www_authenticate_uri
  controllers/ironic_controller.go
  templates/ironic/config/ironic.conf
Labels: lgtm, ok-to-test, approved

#69 Use new lib-common 'PatchInstance' pattern
  api/go.mod
  api/go.sum
  controllers/ironic_controller.go
  controllers/ironicapi_controller.go
  controllers/ironicconductor_controller.go
  go.mod
  go.sum
Labels: lgtm, approved

#70 Drop k8s.io/api to v0.25.5
  api/bases/ironic.openstack.org_ironicapis.yaml
  api/bases/ironic.openstack.org_ironicconductors.yaml
  api/bases/ironic.openstack.org_ironics.yaml
  api/go.mod
  api/go.sum
  config/crd/bases/ironic.openstack.org_ironicapis.yaml
  config/crd/bases/ironic.openstack.org_ironicconductors.yaml
  config/crd/bases/ironic.openstack.org_ironics.yaml
  go.mod
  go.sum
Labels: approved

#74 Only probe JSON-RPC port when use json-rpc transport
  controllers/ironic_controller.go
  pkg/ironicconductor/statefulset.go
Labels: lgtm, approved

#75 Build esp.img with mtools, drop privileged from init container
  pkg/ironic/initcontainer.go
  templates/ironic/bin/conductor-init.sh
Labels: lgtm, approved

#76 Switch from master to zed for ironic images
  config/samples/ironic_v1beta1_ironic.yaml
  config/samples/ironic_v1beta1_ironic_standalone.yaml
  templates/ironic/bin/imagetter.yaml
Labels: lgtm, approved

#82 Refactor conductor service creation
  controllers/ironicconductor_controller.go
  pkg/ironicconductor/service.go
Labels: lgtm, approved

#83 Correctly configure [DEFAULT]isolinux_bin
  templates/ironic/config/ironic.conf
Labels: approved

#87 Use Value from Pod fieldreference for network info
  controllers/ironic_controller.go
  controllers/ironicapi_controller.go
  pkg/ironic/initcontainer.go
  pkg/ironicconductor/statefulset.go
  templates/common/get_net_ip
  templates/ironic/bin/conductor-init.sh
  templates/ironic/bin/provision-network-ip.py
Labels: lgtm, approved
