Repository openstack-k8s-operators/ironic-operator, pull requests merged in 2023-02, with the labels that each got.

#89 Added pre-commit fixes
  .github/create_bundle.sh
  .github/create_opm_index.sh
  .gitignore
  .pre-commit-config.yaml
  api/v1beta1/conditions.go
  api/v1beta1/groupversion_info.go
  config/rbac/service_account.yaml
  hack/boilerplate.go.txt
  templates/common/common.sh
  templates/common/get_net_ip
  templates/ironic/bin/api-prep.sh
  templates/ironic/bin/conductor-init.sh
  templates/ironic/bin/imagetter.yaml
  templates/ironic/bin/init.sh
  templates/ironic/bin/pxe-init.sh
  templates/ironic/config/db-sync-config.json
  templates/ironic/config/dnsmasq-config.json
  templates/ironic/config/dnsmasq.conf
  templates/ironic/config/httpboot-config.json
  templates/ironic/config/ironic-api-config.json
  templates/ironic/config/ironic-api-httpd.conf
  templates/ironic/config/ironic-conductor-config.json
Labels: lgtm, ok-to-test, approved

#92 Set copyright holder in file headers
  api/v1beta1/groupversion_info.go
  api/v1beta1/ironic_types.go
  api/v1beta1/ironicapi_types.go
  api/v1beta1/ironicconductor_types.go
  api/v1beta1/zz_generated.deepcopy.go
  controllers/ironic_controller.go
  controllers/ironicapi_controller.go
  controllers/ironicconductor_controller.go
  controllers/suite_test.go
  hack/boilerplate.go.txt
  main.go
Labels: approved

#95 Standalone and inspector fixes
  api/bases/ironic.openstack.org_ironicconductors.yaml
  api/bases/ironic.openstack.org_ironicinspectors.yaml
  api/bases/ironic.openstack.org_ironics.yaml
  api/v1beta1/ironicinspector_types.go
  config/crd/bases/ironic.openstack.org_ironicconductors.yaml
  config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
  config/crd/bases/ironic.openstack.org_ironics.yaml
  controllers/ironic_controller.go
  controllers/ironicinspector_controller.go
Labels: lgtm, approved

#98 Don't pass ServiceUser to Inspector
  controllers/ironic_controller.go
Labels: lgtm, approved

#97 Don't pass DatabaseUser from ironic to inspector
  controllers/ironic_controller.go
Labels: lgtm, approved

#99 Add Ironic Inspector to config samples
  config/samples/ironic_v1beta1_ironic.yaml
  config/samples/ironic_v1beta1_ironic_standalone.yaml
  config/samples/ironic_v1beta1_ironicinspector.yaml
Labels: lgtm, approved

#101 Return error in ConfigMap creation
  controllers/ironicapi_controller.go
  controllers/ironicconductor_controller.go
  controllers/ironicinspector_controller.go
Labels: lgtm, approved

#103 Get Ingress Domain from API
  config/rbac/role.yaml
  controllers/ironicconductor_controller.go
  controllers/ironicinspector_controller.go
  pkg/ironicconductor/service.go
  pkg/ironicinspector/service.go
  pkg/ironicinspector/statefulset.go
Labels: lgtm, approved

#100 Configure inspector services
  controllers/ironicinspector_controller.go
Labels: lgtm, approved

#104 Run go mod tidy on api/go.mod
  api/go.mod
  api/go.sum
Labels: lgtm, approved

#106 Bump to golang 1.19 and SDK 1.26
  .github/workflows/build-ironic-operator.yaml
  Dockerfile
  Makefile
  api/bases/ironic.openstack.org_ironicapis.yaml
  api/bases/ironic.openstack.org_ironicconductors.yaml
  api/bases/ironic.openstack.org_ironicinspectors.yaml
  api/bases/ironic.openstack.org_ironics.yaml
  api/go.mod
  config/crd/bases/ironic.openstack.org_ironicapis.yaml
  config/crd/bases/ironic.openstack.org_ironicconductors.yaml
  config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
  config/crd/bases/ironic.openstack.org_ironics.yaml
  config/manifests/bases/ironic-operator.clusterserviceversion.yaml
  go.mod
Labels: lgtm, approved

#108 Switch to ginkgo v2
  controllers/suite_test.go
  go.mod
  go.sum
Labels: approved

#109 Fix gen CM error return
  controllers/ironic_controller.go
Labels: lgtm, approved

#111 Configure ironic endpoint for standalone inspector
  api/bases/ironic.openstack.org_ironicapis.yaml
  api/bases/ironic.openstack.org_ironicconductors.yaml
  api/bases/ironic.openstack.org_ironicinspectors.yaml
  api/bases/ironic.openstack.org_ironics.yaml
  api/go.mod
  api/go.sum
  api/v1beta1/ironic_types.go
  api/v1beta1/ironicapi.go
  api/v1beta1/ironicapi_types.go
  api/v1beta1/ironicconductor_types.go
  api/v1beta1/ironicinspector_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/ironic.openstack.org_ironicapis.yaml
  config/crd/bases/ironic.openstack.org_ironicconductors.yaml
  config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
  config/crd/bases/ironic.openstack.org_ironics.yaml
  controllers/ironic_controller.go
  controllers/ironicinspector_controller.go
  templates/ironic/config/ironic.conf
  templates/ironicinspector/config/inspector.conf
Labels: lgtm, approved

#112 Fix Inspector status and APIEndpoints+ServiceIDs
  api/bases/ironic.openstack.org_ironicinspectors.yaml
  api/v1beta1/ironicinspector_types.go
  config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
  controllers/ironic_controller.go
  controllers/ironicapi_controller.go
  controllers/ironicconductor_controller.go
  controllers/ironicinspector_controller.go
Labels: lgtm, approved

#113 Move GetIngressDomain to pkg/ironic/funcs.go
  controllers/ironicconductor_controller.go
  controllers/ironicinspector_controller.go
  pkg/ironic/funcs.go
Labels: lgtm, approved

#115 Set TerminationGracePeriodSeconds on statefulsets
  pkg/ironicconductor/statefulset.go
  pkg/ironicinspector/statefulset.go
Labels: lgtm, approved

#114 Shared TransportURLCreateOrUpdate - pkg/ironic/funcs.go
  controllers/ironic_controller.go
  controllers/ironicinspector_controller.go
  pkg/ironic/funcs.go
Labels: lgtm, approved

#119 Use local operator-sdk
  .github/create_bundle.sh
  .github/workflows/build-ironic-operator.yaml
  Makefile
Labels: lgtm, approved

#120 Use infra-operator
  go.mod
  go.sum
  main.go
  pkg/ironic/funcs.go
Labels: lgtm, approved

#122 Pass GITHUB_TOKEN to install_kustomize.sh to avoid rate-limit
  .github/workflows/build-ironic-operator.yaml
Labels: lgtm, approved

#121 Drop paths-ignore from build operator workflow
  .github/workflows/build-ironic-operator.yaml
Labels: lgtm, approved

#118 Add validating webhook scaffolding
  Makefile
  PROJECT
  api/v1beta1/ironic_webhook.go
  api/v1beta1/webhook_suite_test.go
  api/v1beta1/zz_generated.deepcopy.go
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_service.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  hack/create_self_signed_cert.sh
  main.go
Labels: lgtm, approved

#123 Update pre-commit hook with bashate
  .github/create_bundle.sh
  .pre-commit-config.yaml
  api/v1beta1/ironic_types.go
  api/v1beta1/ironicapi.go
  api/v1beta1/ironicinspector_types.go
  main.go
  templates/ironicinspector/bin/imagetter.yaml
  templates/ironicinspector/bin/init.sh
  templates/ironicinspector/bin/pxe-init.sh
  templates/ironicinspector/config/db-sync-config.json
  templates/ironicinspector/config/dnsmasq-config.json
  templates/ironicinspector/config/httpboot-config.json
  templates/ironicinspector/config/inspector.ipxe
  templates/ironicinspector/config/ironic-inspector-config.json
Labels: lgtm, approved

#117 Inspector reconcilers split up
  controllers/ironicinspector_controller.go
Labels: lgtm, approved

#124 Added ci-operator.yml
  .ci-operator.yaml
Labels: lgtm, approved

#125 Webhook - Validate ConductorGroup is unique
  api/v1beta1/ironic_webhook.go
Labels: lgtm, approved

#126 Add storageClass for Ironic CRD
  api/bases/ironic.openstack.org_ironicconductors.yaml
  api/bases/ironic.openstack.org_ironics.yaml
  api/v1beta1/ironic_types.go
  api/v1beta1/ironicconductor_types.go
  config/crd/bases/ironic.openstack.org_ironicconductors.yaml
  config/crd/bases/ironic.openstack.org_ironics.yaml
  config/samples/ironic_v1beta1_ironic.yaml
  config/samples/ironic_v1beta1_ironic_conductor_groups.yaml
  config/samples/ironic_v1beta1_ironic_standalone.yaml
  controllers/ironic_controller.go
Labels: lgtm, approved

#129 Provide default for storageClass
  api/bases/ironic.openstack.org_ironics.yaml
  api/v1beta1/ironic_types.go
  config/crd/bases/ironic.openstack.org_ironics.yaml
Labels: lgtm, approved

#130 webhook - validatate dhcpRanges
  api/bases/ironic.openstack.org_ironicconductors.yaml
  api/bases/ironic.openstack.org_ironicinspectors.yaml
  api/bases/ironic.openstack.org_ironics.yaml
  api/go.mod
  api/v1beta1/ironic_types.go
  api/v1beta1/ironic_webhook.go
  config/crd/bases/ironic.openstack.org_ironicconductors.yaml
  config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
  config/crd/bases/ironic.openstack.org_ironics.yaml
  controllers/ironicconductor_controller.go
  controllers/ironicinspector_controller.go
  go.mod
  pkg/ironic/funcs.go
Labels: lgtm, approved

#139 Run pre-commit with make
  .pre-commit-config.yaml
  Makefile
Labels: lgtm, approved

#140 Remove DatabaseHostname from inspector SPEC
  api/bases/ironic.openstack.org_ironicinspectors.yaml
  api/bases/ironic.openstack.org_ironics.yaml
  api/v1beta1/ironicinspector_types.go
  config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
  config/crd/bases/ironic.openstack.org_ironics.yaml
  controllers/ironic_controller.go
  pkg/ironicinspector/statefulset.go
Labels: lgtm, approved

#138 Change IronicInspectorReadyCondition value
  api/v1beta1/conditions.go
Labels: approved

#137 Improve logging when creating conductors
  controllers/ironic_controller.go
Labels: lgtm, approved

#143 pre-commit fixes
  .pre-commit-config.yaml
  Makefile
  api/v1beta1/ironic_webhook.go
  api/v1beta1/webhook_suite_test.go
  config/certmanager/certificate.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/webhook/service.yaml
  hack/create_self_signed_cert.sh
  tests/kuttl/common/assert-sample-deployment.yaml
Labels: lgtm, approved

#133 Make Services and Routes owned by Pod - fixes garbage collect on scaling
  controllers/ironicconductor_controller.go
  controllers/ironicinspector_controller.go
Labels: lgtm, approved

#134 Ironic inspector scaling - Maximum 1 replica
  api/bases/ironic.openstack.org_ironicinspectors.yaml
  api/bases/ironic.openstack.org_ironics.yaml
  api/v1beta1/ironic_types.go
  api/v1beta1/ironicinspector_types.go
  config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
  config/crd/bases/ironic.openstack.org_ironics.yaml
  controllers/ironic_controller.go
Labels: lgtm, approved

#142 Add webhook defaulter
  PROJECT
  api/v1beta1/ironic_webhook.go
  api/v1beta1/ironicconductor_types.go
  api/v1beta1/ironicinspector_types.go
  config/default/webhookcainjection_patch.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  controllers/ironic_controller.go
Labels: lgtm, approved

#145 fix typo in golangci-lint name
  Makefile
Labels: lgtm, approved

#141 Make validators externally callable
  api/v1beta1/ironic_webhook.go
Labels: lgtm, approved

#136 Clean up conditions
  controllers/ironic_controller.go
  controllers/ironicconductor_controller.go
Labels: lgtm, approved
