Repository openstack-k8s-operators/ironic-operator, pull requests merged in 2024-02, with the labels that each got.

#378 [go.mod]Bump from v0.3.0 to pseudoversion
  go.mod
  go.sum
Labels: lgtm, approved

#377 force rbac policy to only leverage the new policy
  templates/common/config/ironic.conf
  templates/ironicinspector/config/inspector.conf
Labels: lgtm, approved

#382 Revert ironic-inspector default image
  config/default/manager_default_images.yaml
Labels: lgtm, approved

#384 Controller runtime update
  .ci-operator.yaml
  .github/workflows/build-ironic-operator.yaml
  Dockerfile
  Makefile
  api/bases/ironic.openstack.org_ironicapis.yaml
  api/bases/ironic.openstack.org_ironicconductors.yaml
  api/bases/ironic.openstack.org_ironicinspectors.yaml
  api/bases/ironic.openstack.org_ironicneutronagents.yaml
  api/bases/ironic.openstack.org_ironics.yaml
  api/go.mod
  api/go.sum
  api/v1beta1/ironic_webhook.go
  api/v1beta1/webhook_suite_test.go
  config/crd/bases/ironic.openstack.org_ironicapis.yaml
  config/crd/bases/ironic.openstack.org_ironicconductors.yaml
  config/crd/bases/ironic.openstack.org_ironicinspectors.yaml
  config/crd/bases/ironic.openstack.org_ironicneutronagents.yaml
  config/crd/bases/ironic.openstack.org_ironics.yaml
  controllers/ironicapi_controller.go
  controllers/ironicconductor_controller.go
  controllers/ironicinspector_controller.go
  controllers/ironicneutronagent_controller.go
  go.mod
  go.sum
  main.go
  pkg/ironicconductor/pvc.go
  tests/functional/suite_test.go
Labels: do-not-merge/hold

#388 Unique LeaderElectionID
  main.go
Labels: approved

#389 Bump golangci-lint
  .golangci.yaml
  .pre-commit-config.yaml
Labels: lgtm, approved

#390 [renovate]Remove golang constraint
  renovate.json
Labels: lgtm, approved

#386 This change ensures the `ironic-operator` is built with FIPS compliance
  .prow_ci.env
  Dockerfile
  Makefile
  config/manifests/bases/ironic-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#397 Add eventually to wait for fake ingresscontrollers CRD
  tests/functional/base_test.go
Labels: lgtm, approved

#396 Enable podified zuul jobs against Ironic operator
  zuul.d/projects.yaml
Labels: lgtm, approved

#399 fix: set rbac service role for services to operate properly
  templates/common/config/ironic.conf
Labels: lgtm, approved

#401 Use defaults for force_power_state_during_sync, automated_clean
  templates/common/config/ironic.conf
Labels: lgtm, approved

#404 Regenerate go.mod indirect dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: lgtm, approved

#402 [tlse] TLS database connection
  controllers/ironic_controller.go
  controllers/ironicapi_controller.go
  controllers/ironicconductor_controller.go
  controllers/ironicinspector_controller.go
  controllers/ironicneutronagent_controller.go
  go.mod
  go.sum
  templates/common/bin/common.sh
  templates/ironic/config/db-sync-config.json
  templates/ironicapi/config/ironic-api-config.json
  templates/ironicconductor/config/ironic-conductor-config.json
  templates/ironicinspector/config/db-sync-config.json
  templates/ironicinspector/config/ironic-inspector-config.json
  tests/functional/base_test.go
  tests/functional/ironic_controller_test.go
  tests/functional/ironicapi_controller_test.go
  tests/functional/ironicconductor_controller_test.go
  tests/functional/ironicinspector_controller_test.go
Labels: lgtm, approved

#405 Add IronicSpecCore struct
  api/v1beta1/ironic_types.go
  api/v1beta1/ironic_webhook.go
  api/v1beta1/zz_generated.deepcopy.go
Labels: lgtm, approved
